######################################################################
# Automatically generated by qmake (3.0) ??? ??? 19 18:13:59 2020
######################################################################

TEMPLATE = app
TARGET = qtProgramWithClass
INCLUDEPATH += .

# Input
HEADERS += src/printWidget.hpp
SOURCES += src/main.cpp src/printWidget.cpp
QT += widgets
