######################################################################
# Automatically generated by qmake (3.0) ??? ??? 21 17:49:21 2020
######################################################################

TEMPLATE = app
TARGET = messenger
INCLUDEPATH += .

# Input
HEADERS += src/client.hpp src/manager.hpp
SOURCES += src/client.cpp src/main.cpp src/manager.cpp
QT += widgets
