######################################################################
# Automatically generated by qmake (3.0) ??? ??? 20 12:59:40 2020
######################################################################

TEMPLATE = app
TARGET = qtMessenger
INCLUDEPATH += .

# Input
HEADERS += firstClient.hpp manager.hpp
SOURCES += firstClient.cpp main.cpp manager.cpp
QT += widgets
